version: "3"
services:
  db:
    image: postgres:latest
    #    network_mode: bridge
    #    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    #    expose:
    #      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=library
      - POSTGRES_DB=library
    restart: unless-stopped
  # APP*****************************************
  book-service:
    image: book-service:0.0.1
    #    build: .
    #    expose:
    #      - 8080
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db/library
      - DATASOURCE_USERNAME=library
      - DATASOURCE_PASSWORD=secretpassword
    restart: unless-stopped
#    depends_on:
#      - db
#    links:
#      - db

volumes:
  postgres-data:
